#include "udf.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*
 * CO2_propertiesV3_Python4Property.c
 *
 * Fluent UDF for CO2 property tables generated by CO2_property_2Dtable.py.
 *
 * Supported CSV format:
 *   P(MPa)/T(K), 220.0, 220.5, ...
 *   0.05, value, value, ...
 *
 * Density, viscosity and thermal conductivity are interpolated in (P,T).
 * Cp is handled as Cp(T) at a configurable reference pressure because
 * Fluent's DEFINE_SPECIFIC_HEAT interface does not pass local cell pressure.
 */

#define CSV_MAX_LINE_CHARS 1048576
#define INITIAL_ROW_CAPACITY 512
#define CP_REFERENCE_PRESSURE_PA 14000000.0
#define WARNING_LIMIT 20
#define CO2_MISSING_VALUE 0.0

/*
 * Performance switches:
 *   1 = enable diagnostics during debugging.
 *   0 = disable diagnostics for long production runs.
 *
 * Phase diagnostics only print warnings when an interpolation cell crosses
 * a phase-family boundary. They do not change interpolated property values.
 */
#define ENABLE_PHASE_DIAGNOSTICS 0
#define ENABLE_RANGE_WARNINGS 0

typedef struct {
    int nt;
    int np;
    double *t_grid;    /* K */
    double *p_grid;    /* Pa */
    double *values;    /* row-major: values[ip * nt + it] */
    int loaded;
} Table2D;

typedef struct {
    int nt;
    int np;
    double *t_grid;    /* K */
    double *p_grid;    /* Pa */
    int *phase;        /* row-major phase family */
    int loaded;
} PhaseTable2D;

enum {
    PHASE_UNKNOWN = 0,
    PHASE_GAS = 1,
    PHASE_LIQUID = 2,
    PHASE_SUPERCRITICAL = 3,
    PHASE_TWO_PHASE = 4,
    PHASE_INVALID = 5
};

static Table2D co2_density = {0};
static Table2D co2_viscosity = {0};
static Table2D co2_conductivity = {0};
static Table2D co2_sound_speed = {0};
static Table2D co2_cp_2d = {0};
static PhaseTable2D co2_phase = {0};

static double *cp_ref_t = NULL;
static double *cp_ref = NULL;
static int cp_ref_nt = 0;

static double operating_pressure = 0.0;
static int range_warning_count = 0;
static int phase_warning_count = 0;

static void free_table(Table2D *table)
{
    if (table->t_grid) free(table->t_grid);
    if (table->p_grid) free(table->p_grid);
    if (table->values) free(table->values);
    table->t_grid = NULL;
    table->p_grid = NULL;
    table->values = NULL;
    table->nt = 0;
    table->np = 0;
    table->loaded = 0;
}

static void free_phase_table(PhaseTable2D *table)
{
    if (table->t_grid) free(table->t_grid);
    if (table->p_grid) free(table->p_grid);
    if (table->phase) free(table->phase);
    table->t_grid = NULL;
    table->p_grid = NULL;
    table->phase = NULL;
    table->nt = 0;
    table->np = 0;
    table->loaded = 0;
}

static int count_csv_tokens(char *line)
{
    int count = 0;
    char *token = strtok(line, ",\n\r");
    while (token != NULL) {
        count++;
        token = strtok(NULL, ",\n\r");
    }
    return count;
}

static int parse_phase_family(const char *text)
{
    if (text == NULL) return PHASE_UNKNOWN;
    if (strstr(text, "invalid") != NULL) return PHASE_INVALID;
    if (strstr(text, "two") != NULL || strstr(text, "phase_twophase") != NULL) return PHASE_TWO_PHASE;
    if (strstr(text, "supercritical") != NULL) {
        if (strstr(text, "gas") != NULL) return PHASE_GAS;
        if (strstr(text, "liquid") != NULL) return PHASE_LIQUID;
        return PHASE_SUPERCRITICAL;
    }
    if (strstr(text, "gas") != NULL) return PHASE_GAS;
    if (strstr(text, "liquid") != NULL) return PHASE_LIQUID;
    if (strstr(text, "critical") != NULL) return PHASE_SUPERCRITICAL;
    return PHASE_UNKNOWN;
}

static int read_table_2d(const char *filename, Table2D *table)
{
    FILE *fp;
    char *line;
    char *header_copy;
    char *token;
    int nt, row_capacity, row_count, j;
    double *new_values;

    fp = fopen(filename, "r");
    if (fp == NULL) {
        Message("\n[CO2-UDF Error] Cannot open %s\n", filename);
        return 0;
    }

    line = (char*)malloc(CSV_MAX_LINE_CHARS);
    if (line == NULL) {
        Message("\n[CO2-UDF Error] Failed to allocate CSV line buffer.\n");
        fclose(fp);
        return 0;
    }

    if (fgets(line, CSV_MAX_LINE_CHARS, fp) == NULL) {
        Message("\n[CO2-UDF Error] Empty CSV file: %s\n", filename);
        free(line);
        fclose(fp);
        return 0;
    }

    header_copy = (char*)malloc(strlen(line) + 1);
    if (header_copy == NULL) {
        Message("\n[CO2-UDF Error] Failed to allocate header buffer.\n");
        free(line);
        fclose(fp);
        return 0;
    }
    strcpy(header_copy, line);
    nt = count_csv_tokens(header_copy) - 1;
    free(header_copy);

    if (nt < 2) {
        Message("\n[CO2-UDF Error] Invalid temperature header in %s\n", filename);
        free(line);
        fclose(fp);
        return 0;
    }

    free_table(table);
    table->nt = nt;
    table->t_grid = (double*)malloc(sizeof(double) * nt);

    token = strtok(line, ",\n\r"); /* first token: P(MPa)/T(K) */
    for (j = 0; j < nt; j++) {
        token = strtok(NULL, ",\n\r");
        if (token == NULL) {
            Message("\n[CO2-UDF Error] Temperature header length mismatch in %s\n", filename);
            free(line);
            fclose(fp);
            free_table(table);
            return 0;
        }
        table->t_grid[j] = atof(token);
    }

    row_capacity = INITIAL_ROW_CAPACITY;
    row_count = 0;
    table->p_grid = (double*)malloc(sizeof(double) * row_capacity);
    table->values = (double*)malloc(sizeof(double) * row_capacity * nt);

    if (table->t_grid == NULL || table->p_grid == NULL || table->values == NULL) {
        Message("\n[CO2-UDF Error] Failed to allocate table arrays for %s\n", filename);
        free(line);
        fclose(fp);
        free_table(table);
        return 0;
    }

    while (fgets(line, CSV_MAX_LINE_CHARS, fp) != NULL) {
        token = strtok(line, ",\n\r");
        if (token == NULL) continue;

        if (row_count >= row_capacity) {
            row_capacity *= 2;
            table->p_grid = (double*)realloc(table->p_grid, sizeof(double) * row_capacity);
            new_values = (double*)realloc(table->values, sizeof(double) * row_capacity * nt);
            if (table->p_grid == NULL || new_values == NULL) {
                Message("\n[CO2-UDF Error] Failed to grow table arrays for %s\n", filename);
                free(line);
                fclose(fp);
                free_table(table);
                return 0;
            }
            table->values = new_values;
        }

        table->p_grid[row_count] = atof(token) * 1.0e6; /* CSV MPa -> Pa */
        for (j = 0; j < nt; j++) {
            token = strtok(NULL, ",\n\r");
            table->values[row_count * nt + j] = (token != NULL) ? atof(token) : CO2_MISSING_VALUE;
        }
        row_count++;
    }

    table->np = row_count;
    table->loaded = (table->np >= 2 && table->nt >= 2);
    free(line);
    fclose(fp);

    if (!table->loaded) {
        Message("\n[CO2-UDF Error] Insufficient rows in %s\n", filename);
        free_table(table);
        return 0;
    }

    Message("\n[CO2-UDF] Loaded %s: np=%d, nt=%d, P=[%.6g, %.6g] Pa, T=[%.6g, %.6g] K\n",
            filename, table->np, table->nt,
            table->p_grid[0], table->p_grid[table->np - 1],
            table->t_grid[0], table->t_grid[table->nt - 1]);
    return 1;
}

#if ENABLE_PHASE_DIAGNOSTICS
static int read_phase_table(const char *filename, PhaseTable2D *phase_table, const Table2D *reference)
{
    FILE *fp;
    char *line;
    char *token;
    int i, j;

    if (reference == NULL || !reference->loaded) {
        Message("\n[CO2-UDF Warning] Reference property table is not loaded. Phase diagnostics disabled.\n");
        return 0;
    }

    fp = fopen(filename, "r");
    if (fp == NULL) {
        Message("\n[CO2-UDF Warning] Cannot open %s. Phase diagnostics disabled.\n", filename);
        return 0;
    }

    line = (char*)malloc(CSV_MAX_LINE_CHARS);
    if (line == NULL) {
        fclose(fp);
        return 0;
    }

    free_phase_table(phase_table);
    phase_table->nt = reference->nt;
    phase_table->np = reference->np;
    phase_table->t_grid = (double*)malloc(sizeof(double) * reference->nt);
    phase_table->p_grid = (double*)malloc(sizeof(double) * reference->np);
    phase_table->phase = (int*)malloc(sizeof(int) * reference->nt * reference->np);

    if (phase_table->t_grid == NULL || phase_table->p_grid == NULL || phase_table->phase == NULL) {
        Message("\n[CO2-UDF Warning] Failed to allocate phase table.\n");
        free(line);
        fclose(fp);
        free_phase_table(phase_table);
        return 0;
    }

    for (j = 0; j < reference->nt; j++) phase_table->t_grid[j] = reference->t_grid[j];
    for (i = 0; i < reference->np; i++) phase_table->p_grid[i] = reference->p_grid[i];

    fgets(line, CSV_MAX_LINE_CHARS, fp); /* header */
    for (i = 0; i < reference->np; i++) {
        if (fgets(line, CSV_MAX_LINE_CHARS, fp) == NULL) break;
        token = strtok(line, ",\n\r"); /* pressure */
        for (j = 0; j < reference->nt; j++) {
            token = strtok(NULL, ",\n\r");
            phase_table->phase[i * reference->nt + j] = parse_phase_family(token);
        }
    }

    phase_table->loaded = 1;
    free(line);
    fclose(fp);
    Message("\n[CO2-UDF] Loaded %s for phase diagnostics.\n", filename);
    return 1;
}
#endif

static int find_interval(const double *grid, int n, double x, int *clamped)
{
    int lo = 0;
    int hi = n - 1;
    int mid;

    *clamped = 0;
    if (x <= grid[0]) {
        *clamped = 1;
        return 0;
    }
    if (x >= grid[n - 1]) {
        *clamped = 1;
        return n - 2;
    }

    while (hi - lo > 1) {
        mid = (lo + hi) / 2;
        if (grid[mid] <= x) lo = mid;
        else hi = mid;
    }
    return lo;
}

#if ENABLE_PHASE_DIAGNOSTICS
static int cell_crosses_phase_boundary(const PhaseTable2D *phase_table, int ip, int it)
{
    int nt, p00, p10, p01, p11;
    if (phase_table == NULL || !phase_table->loaded) return 0;

    nt = phase_table->nt;
    p00 = phase_table->phase[ip * nt + it];
    p10 = phase_table->phase[ip * nt + it + 1];
    p01 = phase_table->phase[(ip + 1) * nt + it];
    p11 = phase_table->phase[(ip + 1) * nt + it + 1];

    return !(p00 == p10 && p00 == p01 && p00 == p11);
}
#endif

static double interpolate_table_2d(double t, double p, const Table2D *table, const char *property_name)
{
    int it, ip, t_clamped, p_clamped;
    double t0, t1, p0, p1;
    double u, v;
    double f00, f10, f01, f11;
    int nt;

    if (table == NULL || !table->loaded) {
        if (range_warning_count < WARNING_LIMIT) {
            Message("\n[CO2-UDF Warning] Property table %s is not loaded.\n", property_name);
            range_warning_count++;
        }
        return 0.0;
    }

    it = find_interval(table->t_grid, table->nt, t, &t_clamped);
    ip = find_interval(table->p_grid, table->np, p, &p_clamped);

#if ENABLE_RANGE_WARNINGS
    if ((t_clamped || p_clamped) && range_warning_count < WARNING_LIMIT) {
        Message("\n[CO2-UDF Warning] %s request outside table range: T=%.6g K, P=%.6g Pa. Boundary value used.\n",
                property_name, t, p);
        range_warning_count++;
    }
#endif

#if ENABLE_PHASE_DIAGNOSTICS
    if (cell_crosses_phase_boundary(&co2_phase, ip, it) && phase_warning_count < WARNING_LIMIT) {
        Message("\n[CO2-UDF Warning] %s interpolation cell crosses phase boundary near T=%.6g K, P=%.6g Pa.\n",
                property_name, t, p);
        phase_warning_count++;
    }
#endif

    t0 = table->t_grid[it];
    t1 = table->t_grid[it + 1];
    p0 = table->p_grid[ip];
    p1 = table->p_grid[ip + 1];
    u = (t <= t0) ? 0.0 : ((t >= t1) ? 1.0 : (t - t0) / (t1 - t0));
    v = (p <= p0) ? 0.0 : ((p >= p1) ? 1.0 : (p - p0) / (p1 - p0));

    nt = table->nt;
    f00 = table->values[ip * nt + it];
    f10 = table->values[ip * nt + it + 1];
    f01 = table->values[(ip + 1) * nt + it];
    f11 = table->values[(ip + 1) * nt + it + 1];

    return (1.0 - u) * (1.0 - v) * f00
         + u * (1.0 - v) * f10
         + (1.0 - u) * v * f01
         + u * v * f11;
}

static double interpolate_1d(const double *x, const double *y, int n, double xq)
{
    int i, clamped;
    double u;
    if (x == NULL || y == NULL || n < 2) return 0.0;

    i = find_interval(x, n, xq, &clamped);
    if (xq <= x[i]) u = 0.0;
    else if (xq >= x[i + 1]) u = 1.0;
    else u = (xq - x[i]) / (x[i + 1] - x[i]);
    return y[i] * (1.0 - u) + y[i + 1] * u;
}

static int nearest_pressure_row(const Table2D *table, double p_ref)
{
    int i, best = 0;
    double best_diff, diff;
    if (table == NULL || !table->loaded) return 0;

    best_diff = fabs(table->p_grid[0] - p_ref);
    for (i = 1; i < table->np; i++) {
        diff = fabs(table->p_grid[i] - p_ref);
        if (diff < best_diff) {
            best_diff = diff;
            best = i;
        }
    }
    return best;
}

static void build_cp_reference_curve(void)
{
    int i, row;
    if (!co2_cp_2d.loaded) return;

    if (cp_ref_t) free(cp_ref_t);
    if (cp_ref) free(cp_ref);

    cp_ref_nt = co2_cp_2d.nt;
    cp_ref_t = (double*)malloc(sizeof(double) * cp_ref_nt);
    cp_ref = (double*)malloc(sizeof(double) * cp_ref_nt);

    if (cp_ref_t == NULL || cp_ref == NULL) {
        Message("\n[CO2-UDF Error] Failed to allocate Cp reference curve.\n");
        cp_ref_nt = 0;
        return;
    }

    row = nearest_pressure_row(&co2_cp_2d, CP_REFERENCE_PRESSURE_PA);
    for (i = 0; i < cp_ref_nt; i++) {
        cp_ref_t[i] = co2_cp_2d.t_grid[i];
        cp_ref[i] = co2_cp_2d.values[row * co2_cp_2d.nt + i];
    }

    Message("\n[CO2-UDF] Cp(T) reference curve uses nearest pressure row: %.6g Pa.\n",
            co2_cp_2d.p_grid[row]);
}

static double integrate_cp(double t0, double t1)
{
    int i_start, i_end, clamped0, clamped1, i;
    double a, b, integral, cp_a, cp_b;
    int sign = 1;

    if (cp_ref_t == NULL || cp_ref == NULL || cp_ref_nt < 2) return 0.0;
    if (t0 == t1) return 0.0;
    if (t1 < t0) {
        double tmp = t0;
        t0 = t1;
        t1 = tmp;
        sign = -1;
    }

    if (t0 < cp_ref_t[0]) t0 = cp_ref_t[0];
    if (t1 > cp_ref_t[cp_ref_nt - 1]) t1 = cp_ref_t[cp_ref_nt - 1];

    i_start = find_interval(cp_ref_t, cp_ref_nt, t0, &clamped0);
    i_end = find_interval(cp_ref_t, cp_ref_nt, t1, &clamped1);

    integral = 0.0;
    for (i = i_start; i <= i_end; i++) {
        a = (i == i_start) ? t0 : cp_ref_t[i];
        b = (i == i_end) ? t1 : cp_ref_t[i + 1];
        if (b <= a) continue;
        cp_a = interpolate_1d(cp_ref_t, cp_ref, cp_ref_nt, a);
        cp_b = interpolate_1d(cp_ref_t, cp_ref, cp_ref_nt, b);
        integral += 0.5 * (cp_a + cp_b) * (b - a);
    }

    return sign * integral;
}

DEFINE_ON_DEMAND(CO2_import_property_tables)
{
    operating_pressure = RP_Get_Real("operating-pressure");
    range_warning_count = 0;
    phase_warning_count = 0;

    read_table_2d("co2_density.csv", &co2_density);
    read_table_2d("co2_viscosity.csv", &co2_viscosity);
    read_table_2d("co2_conductivity.csv", &co2_conductivity);
    read_table_2d("co2_sound_speed.csv", &co2_sound_speed);
    read_table_2d("co2_cp.csv", &co2_cp_2d);
#if ENABLE_PHASE_DIAGNOSTICS
    read_phase_table("co2_phase.csv", &co2_phase, &co2_density);
#else
    Message("\n[CO2-UDF] Phase diagnostics disabled by ENABLE_PHASE_DIAGNOSTICS=0.\n");
#endif
    build_cp_reference_curve();

    Message("\n[CO2-UDF] Import complete. Operating pressure = %.6g Pa.\n", operating_pressure);
}

DEFINE_PROPERTY(CO2_table_density, c, thread)
{
    double t = C_T(c, thread);
    double p_abs = C_P(c, thread) + operating_pressure;
    return interpolate_table_2d(t, p_abs, &co2_density, "density");
}

DEFINE_PROPERTY(CO2_table_viscosity, c, thread)
{
    double t = C_T(c, thread);
    double p_abs = C_P(c, thread) + operating_pressure;
    return interpolate_table_2d(t, p_abs, &co2_viscosity, "viscosity");
}

DEFINE_PROPERTY(CO2_table_thermal_conductivity, c, thread)
{
    double t = C_T(c, thread);
    double p_abs = C_P(c, thread) + operating_pressure;
    return interpolate_table_2d(t, p_abs, &co2_conductivity, "thermal conductivity");
}

DEFINE_PROPERTY(CO2_table_sound_speed, c, thread)
{
    double t = C_T(c, thread);
    double p_abs = C_P(c, thread) + operating_pressure;
    return interpolate_table_2d(t, p_abs, &co2_sound_speed, "speed of sound");
}

DEFINE_SPECIFIC_HEAT(CO2_table_cp, T, Tref, h, yi)
{
    double cp = interpolate_1d(cp_ref_t, cp_ref, cp_ref_nt, T);
    *h = cp * (T - Tref);
    return cp;
}

DEFINE_ON_DEMAND(CO2_test_property_tables)
{
    double test_t = 623.15;
    double test_p = 14.0e6;
    double rho, mu, k, a, cp;

    if (!co2_density.loaded || cp_ref == NULL) {
        Message("\n[CO2-UDF Warning] Please run CO2_import_property_tables first.\n");
        return;
    }

    rho = interpolate_table_2d(test_t, test_p, &co2_density, "density");
    mu = interpolate_table_2d(test_t, test_p, &co2_viscosity, "viscosity");
    k = interpolate_table_2d(test_t, test_p, &co2_conductivity, "thermal conductivity");
    a = interpolate_table_2d(test_t, test_p, &co2_sound_speed, "speed of sound");
    cp = interpolate_1d(cp_ref_t, cp_ref, cp_ref_nt, test_t);

    Message("\n================ CO2 table test ================\n");
    Message("Test point: T = %.3f K, P = %.6f MPa\n", test_t, test_p / 1.0e6);
    Message("Density              = %.9g kg/m3\n", rho);
    Message("Viscosity            = %.9g Pa s\n", mu);
    Message("Thermal conductivity = %.9g W/m/K\n", k);
    Message("Speed of sound       = %.9g m/s\n", a);
    Message("Cp(reference P)      = %.9g J/kg/K\n", cp);
    Message("================================================\n\n");
}
